runtime: php
env: flex

runtime_config:
  document_root: .
  
network:
  instance_tag: webengineapp
  name: production-vpc
  subnetwork_name: europe-west1-internal-prod 
 
beta_settings:
  cloud_sql_instances: "lemonde-app-123:europe-west1:lemonde-sql-prod"
 
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6
    
resources:
  cpu: 4
  memory_gb: 2.0
  disk_size_gb: 10
